import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";
import ThemeToggle from "@/components/ThemeToggle";
import { AuthProvider } from "@/lib/auth";

// Applied before paint so a saved light theme doesn't flash dark first.
const themeScript = `(function(){try{if(localStorage.getItem('ms_theme')==='light')document.documentElement.classList.add('light')}catch(e){}})()`;

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000"),
  title: "MarketStack — your repo + domain → a full marketing suite",
  description:
    "Paste a GitHub repo and a domain. Get CRO, SEO, copy, emails, ads, a launch plan and a 90-day marketing plan — generated by Claude marketing skills.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="font-sans antialiased">
        <AuthProvider>
          <SmoothScroll>{children}</SmoothScroll>
          <ThemeToggle />
        </AuthProvider>
      </body>
    </html>
  );
}
